/* soapMedia2BindingProxy.h
   Generated by gSOAP 2.8.131 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapMedia2BindingProxy_H
#define soapMedia2BindingProxy_H
#include "soapH.h"

    class SOAP_CMAC Media2BindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'Media2BindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvif.h, if any
        /// Construct a proxy with new managing context
        Media2BindingProxy();
        /// Copy constructor
        Media2BindingProxy(const Media2BindingProxy& rhs);
        /// Construct proxy given a shared managing context
        Media2BindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        Media2BindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        Media2BindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        Media2BindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        Media2BindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        Media2BindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~Media2BindingProxy();
        /// Initializer used by constructors
        virtual void Media2BindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual Media2BindingProxy *copy();
        /// Copy assignment
        Media2BindingProxy& operator=(const Media2BindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'GetServiceCapabilities' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetServiceCapabilities(_ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse) { return this->GetServiceCapabilities(NULL, NULL, ns1__GetServiceCapabilities, ns1__GetServiceCapabilitiesResponse); }
        /// Web service synchronous operation 'GetServiceCapabilities' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse) { return this->send_GetServiceCapabilities(soap_endpoint_url, soap_action, ns1__GetServiceCapabilities) || this->recv_GetServiceCapabilities(ns1__GetServiceCapabilitiesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetServiceCapabilities' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetServiceCapabilities(const char *soap_endpoint_url, const char *soap_action, _ns1__GetServiceCapabilities *ns1__GetServiceCapabilities);
        /// Web service asynchronous operation 'recv_GetServiceCapabilities' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetServiceCapabilities(_ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse);
        //
        /// Web service synchronous operation 'CreateProfile' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreateProfile(_ns1__CreateProfile *ns1__CreateProfile, _ns1__CreateProfileResponse &ns1__CreateProfileResponse) { return this->CreateProfile(NULL, NULL, ns1__CreateProfile, ns1__CreateProfileResponse); }
        /// Web service synchronous operation 'CreateProfile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreateProfile(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateProfile *ns1__CreateProfile, _ns1__CreateProfileResponse &ns1__CreateProfileResponse) { return this->send_CreateProfile(soap_endpoint_url, soap_action, ns1__CreateProfile) || this->recv_CreateProfile(ns1__CreateProfileResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreateProfile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreateProfile(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateProfile *ns1__CreateProfile);
        /// Web service asynchronous operation 'recv_CreateProfile' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreateProfile(_ns1__CreateProfileResponse &ns1__CreateProfileResponse);
        //
        /// Web service synchronous operation 'GetProfiles' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetProfiles(_ns1__GetProfiles *ns1__GetProfiles, _ns1__GetProfilesResponse &ns1__GetProfilesResponse) { return this->GetProfiles(NULL, NULL, ns1__GetProfiles, ns1__GetProfilesResponse); }
        /// Web service synchronous operation 'GetProfiles' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetProfiles(const char *soap_endpoint_url, const char *soap_action, _ns1__GetProfiles *ns1__GetProfiles, _ns1__GetProfilesResponse &ns1__GetProfilesResponse) { return this->send_GetProfiles(soap_endpoint_url, soap_action, ns1__GetProfiles) || this->recv_GetProfiles(ns1__GetProfilesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetProfiles' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetProfiles(const char *soap_endpoint_url, const char *soap_action, _ns1__GetProfiles *ns1__GetProfiles);
        /// Web service asynchronous operation 'recv_GetProfiles' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetProfiles(_ns1__GetProfilesResponse &ns1__GetProfilesResponse);
        //
        /// Web service synchronous operation 'AddConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int AddConfiguration(_ns1__AddConfiguration *ns1__AddConfiguration, _ns1__AddConfigurationResponse &ns1__AddConfigurationResponse) { return this->AddConfiguration(NULL, NULL, ns1__AddConfiguration, ns1__AddConfigurationResponse); }
        /// Web service synchronous operation 'AddConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int AddConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__AddConfiguration *ns1__AddConfiguration, _ns1__AddConfigurationResponse &ns1__AddConfigurationResponse) { return this->send_AddConfiguration(soap_endpoint_url, soap_action, ns1__AddConfiguration) || this->recv_AddConfiguration(ns1__AddConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_AddConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_AddConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__AddConfiguration *ns1__AddConfiguration);
        /// Web service asynchronous operation 'recv_AddConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_AddConfiguration(_ns1__AddConfigurationResponse &ns1__AddConfigurationResponse);
        //
        /// Web service synchronous operation 'RemoveConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveConfiguration(_ns1__RemoveConfiguration *ns1__RemoveConfiguration, _ns1__RemoveConfigurationResponse &ns1__RemoveConfigurationResponse) { return this->RemoveConfiguration(NULL, NULL, ns1__RemoveConfiguration, ns1__RemoveConfigurationResponse); }
        /// Web service synchronous operation 'RemoveConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int RemoveConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__RemoveConfiguration *ns1__RemoveConfiguration, _ns1__RemoveConfigurationResponse &ns1__RemoveConfigurationResponse) { return this->send_RemoveConfiguration(soap_endpoint_url, soap_action, ns1__RemoveConfiguration) || this->recv_RemoveConfiguration(ns1__RemoveConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_RemoveConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_RemoveConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__RemoveConfiguration *ns1__RemoveConfiguration);
        /// Web service asynchronous operation 'recv_RemoveConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_RemoveConfiguration(_ns1__RemoveConfigurationResponse &ns1__RemoveConfigurationResponse);
        //
        /// Web service synchronous operation 'DeleteProfile' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteProfile(_ns1__DeleteProfile *ns1__DeleteProfile, _ns1__DeleteProfileResponse &ns1__DeleteProfileResponse) { return this->DeleteProfile(NULL, NULL, ns1__DeleteProfile, ns1__DeleteProfileResponse); }
        /// Web service synchronous operation 'DeleteProfile' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteProfile(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteProfile *ns1__DeleteProfile, _ns1__DeleteProfileResponse &ns1__DeleteProfileResponse) { return this->send_DeleteProfile(soap_endpoint_url, soap_action, ns1__DeleteProfile) || this->recv_DeleteProfile(ns1__DeleteProfileResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteProfile' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteProfile(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteProfile *ns1__DeleteProfile);
        /// Web service asynchronous operation 'recv_DeleteProfile' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteProfile(_ns1__DeleteProfileResponse &ns1__DeleteProfileResponse);
        //
        /// Web service synchronous operation 'GetVideoSourceConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceConfigurations(ns1__GetConfiguration *ns1__GetVideoSourceConfigurations, _ns1__GetVideoSourceConfigurationsResponse &ns1__GetVideoSourceConfigurationsResponse) { return this->GetVideoSourceConfigurations(NULL, NULL, ns1__GetVideoSourceConfigurations, ns1__GetVideoSourceConfigurationsResponse); }
        /// Web service synchronous operation 'GetVideoSourceConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetVideoSourceConfigurations, _ns1__GetVideoSourceConfigurationsResponse &ns1__GetVideoSourceConfigurationsResponse) { return this->send_GetVideoSourceConfigurations(soap_endpoint_url, soap_action, ns1__GetVideoSourceConfigurations) || this->recv_GetVideoSourceConfigurations(ns1__GetVideoSourceConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoSourceConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoSourceConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetVideoSourceConfigurations);
        /// Web service asynchronous operation 'recv_GetVideoSourceConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoSourceConfigurations(_ns1__GetVideoSourceConfigurationsResponse &ns1__GetVideoSourceConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetVideoEncoderConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoEncoderConfigurations(ns1__GetConfiguration *ns1__GetVideoEncoderConfigurations, _ns1__GetVideoEncoderConfigurationsResponse &ns1__GetVideoEncoderConfigurationsResponse) { return this->GetVideoEncoderConfigurations(NULL, NULL, ns1__GetVideoEncoderConfigurations, ns1__GetVideoEncoderConfigurationsResponse); }
        /// Web service synchronous operation 'GetVideoEncoderConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoEncoderConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetVideoEncoderConfigurations, _ns1__GetVideoEncoderConfigurationsResponse &ns1__GetVideoEncoderConfigurationsResponse) { return this->send_GetVideoEncoderConfigurations(soap_endpoint_url, soap_action, ns1__GetVideoEncoderConfigurations) || this->recv_GetVideoEncoderConfigurations(ns1__GetVideoEncoderConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoEncoderConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoEncoderConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetVideoEncoderConfigurations);
        /// Web service asynchronous operation 'recv_GetVideoEncoderConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoEncoderConfigurations(_ns1__GetVideoEncoderConfigurationsResponse &ns1__GetVideoEncoderConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetAudioSourceConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSourceConfigurations(ns1__GetConfiguration *ns1__GetAudioSourceConfigurations, _ns1__GetAudioSourceConfigurationsResponse &ns1__GetAudioSourceConfigurationsResponse) { return this->GetAudioSourceConfigurations(NULL, NULL, ns1__GetAudioSourceConfigurations, ns1__GetAudioSourceConfigurationsResponse); }
        /// Web service synchronous operation 'GetAudioSourceConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSourceConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioSourceConfigurations, _ns1__GetAudioSourceConfigurationsResponse &ns1__GetAudioSourceConfigurationsResponse) { return this->send_GetAudioSourceConfigurations(soap_endpoint_url, soap_action, ns1__GetAudioSourceConfigurations) || this->recv_GetAudioSourceConfigurations(ns1__GetAudioSourceConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioSourceConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioSourceConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioSourceConfigurations);
        /// Web service asynchronous operation 'recv_GetAudioSourceConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioSourceConfigurations(_ns1__GetAudioSourceConfigurationsResponse &ns1__GetAudioSourceConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetAudioEncoderConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioEncoderConfigurations(ns1__GetConfiguration *ns1__GetAudioEncoderConfigurations, _ns1__GetAudioEncoderConfigurationsResponse &ns1__GetAudioEncoderConfigurationsResponse) { return this->GetAudioEncoderConfigurations(NULL, NULL, ns1__GetAudioEncoderConfigurations, ns1__GetAudioEncoderConfigurationsResponse); }
        /// Web service synchronous operation 'GetAudioEncoderConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioEncoderConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioEncoderConfigurations, _ns1__GetAudioEncoderConfigurationsResponse &ns1__GetAudioEncoderConfigurationsResponse) { return this->send_GetAudioEncoderConfigurations(soap_endpoint_url, soap_action, ns1__GetAudioEncoderConfigurations) || this->recv_GetAudioEncoderConfigurations(ns1__GetAudioEncoderConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioEncoderConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioEncoderConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioEncoderConfigurations);
        /// Web service asynchronous operation 'recv_GetAudioEncoderConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioEncoderConfigurations(_ns1__GetAudioEncoderConfigurationsResponse &ns1__GetAudioEncoderConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetAnalyticsConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAnalyticsConfigurations(ns1__GetConfiguration *ns1__GetAnalyticsConfigurations, _ns1__GetAnalyticsConfigurationsResponse &ns1__GetAnalyticsConfigurationsResponse) { return this->GetAnalyticsConfigurations(NULL, NULL, ns1__GetAnalyticsConfigurations, ns1__GetAnalyticsConfigurationsResponse); }
        /// Web service synchronous operation 'GetAnalyticsConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAnalyticsConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAnalyticsConfigurations, _ns1__GetAnalyticsConfigurationsResponse &ns1__GetAnalyticsConfigurationsResponse) { return this->send_GetAnalyticsConfigurations(soap_endpoint_url, soap_action, ns1__GetAnalyticsConfigurations) || this->recv_GetAnalyticsConfigurations(ns1__GetAnalyticsConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAnalyticsConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAnalyticsConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAnalyticsConfigurations);
        /// Web service asynchronous operation 'recv_GetAnalyticsConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAnalyticsConfigurations(_ns1__GetAnalyticsConfigurationsResponse &ns1__GetAnalyticsConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetMetadataConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetMetadataConfigurations(ns1__GetConfiguration *ns1__GetMetadataConfigurations, _ns1__GetMetadataConfigurationsResponse &ns1__GetMetadataConfigurationsResponse) { return this->GetMetadataConfigurations(NULL, NULL, ns1__GetMetadataConfigurations, ns1__GetMetadataConfigurationsResponse); }
        /// Web service synchronous operation 'GetMetadataConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetMetadataConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetMetadataConfigurations, _ns1__GetMetadataConfigurationsResponse &ns1__GetMetadataConfigurationsResponse) { return this->send_GetMetadataConfigurations(soap_endpoint_url, soap_action, ns1__GetMetadataConfigurations) || this->recv_GetMetadataConfigurations(ns1__GetMetadataConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetMetadataConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetMetadataConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetMetadataConfigurations);
        /// Web service asynchronous operation 'recv_GetMetadataConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetMetadataConfigurations(_ns1__GetMetadataConfigurationsResponse &ns1__GetMetadataConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetAudioOutputConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputConfigurations(ns1__GetConfiguration *ns1__GetAudioOutputConfigurations, _ns1__GetAudioOutputConfigurationsResponse &ns1__GetAudioOutputConfigurationsResponse) { return this->GetAudioOutputConfigurations(NULL, NULL, ns1__GetAudioOutputConfigurations, ns1__GetAudioOutputConfigurationsResponse); }
        /// Web service synchronous operation 'GetAudioOutputConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioOutputConfigurations, _ns1__GetAudioOutputConfigurationsResponse &ns1__GetAudioOutputConfigurationsResponse) { return this->send_GetAudioOutputConfigurations(soap_endpoint_url, soap_action, ns1__GetAudioOutputConfigurations) || this->recv_GetAudioOutputConfigurations(ns1__GetAudioOutputConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioOutputConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioOutputConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioOutputConfigurations);
        /// Web service asynchronous operation 'recv_GetAudioOutputConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioOutputConfigurations(_ns1__GetAudioOutputConfigurationsResponse &ns1__GetAudioOutputConfigurationsResponse);
        //
        /// Web service synchronous operation 'GetAudioDecoderConfigurations' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioDecoderConfigurations(ns1__GetConfiguration *ns1__GetAudioDecoderConfigurations, _ns1__GetAudioDecoderConfigurationsResponse &ns1__GetAudioDecoderConfigurationsResponse) { return this->GetAudioDecoderConfigurations(NULL, NULL, ns1__GetAudioDecoderConfigurations, ns1__GetAudioDecoderConfigurationsResponse); }
        /// Web service synchronous operation 'GetAudioDecoderConfigurations' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioDecoderConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioDecoderConfigurations, _ns1__GetAudioDecoderConfigurationsResponse &ns1__GetAudioDecoderConfigurationsResponse) { return this->send_GetAudioDecoderConfigurations(soap_endpoint_url, soap_action, ns1__GetAudioDecoderConfigurations) || this->recv_GetAudioDecoderConfigurations(ns1__GetAudioDecoderConfigurationsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioDecoderConfigurations' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioDecoderConfigurations(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioDecoderConfigurations);
        /// Web service asynchronous operation 'recv_GetAudioDecoderConfigurations' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioDecoderConfigurations(_ns1__GetAudioDecoderConfigurationsResponse &ns1__GetAudioDecoderConfigurationsResponse);
        //
        /// Web service synchronous operation 'SetVideoSourceConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoSourceConfiguration(_ns1__SetVideoSourceConfiguration *ns1__SetVideoSourceConfiguration, ns1__SetConfigurationResponse &ns1__SetVideoSourceConfigurationResponse) { return this->SetVideoSourceConfiguration(NULL, NULL, ns1__SetVideoSourceConfiguration, ns1__SetVideoSourceConfigurationResponse); }
        /// Web service synchronous operation 'SetVideoSourceConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetVideoSourceConfiguration *ns1__SetVideoSourceConfiguration, ns1__SetConfigurationResponse &ns1__SetVideoSourceConfigurationResponse) { return this->send_SetVideoSourceConfiguration(soap_endpoint_url, soap_action, ns1__SetVideoSourceConfiguration) || this->recv_SetVideoSourceConfiguration(ns1__SetVideoSourceConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetVideoSourceConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetVideoSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetVideoSourceConfiguration *ns1__SetVideoSourceConfiguration);
        /// Web service asynchronous operation 'recv_SetVideoSourceConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetVideoSourceConfiguration(ns1__SetConfigurationResponse &ns1__SetVideoSourceConfigurationResponse);
        //
        /// Web service synchronous operation 'SetVideoEncoderConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoEncoderConfiguration(_ns1__SetVideoEncoderConfiguration *ns1__SetVideoEncoderConfiguration, ns1__SetConfigurationResponse &ns1__SetVideoEncoderConfigurationResponse) { return this->SetVideoEncoderConfiguration(NULL, NULL, ns1__SetVideoEncoderConfiguration, ns1__SetVideoEncoderConfigurationResponse); }
        /// Web service synchronous operation 'SetVideoEncoderConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoEncoderConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetVideoEncoderConfiguration *ns1__SetVideoEncoderConfiguration, ns1__SetConfigurationResponse &ns1__SetVideoEncoderConfigurationResponse) { return this->send_SetVideoEncoderConfiguration(soap_endpoint_url, soap_action, ns1__SetVideoEncoderConfiguration) || this->recv_SetVideoEncoderConfiguration(ns1__SetVideoEncoderConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetVideoEncoderConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetVideoEncoderConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetVideoEncoderConfiguration *ns1__SetVideoEncoderConfiguration);
        /// Web service asynchronous operation 'recv_SetVideoEncoderConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetVideoEncoderConfiguration(ns1__SetConfigurationResponse &ns1__SetVideoEncoderConfigurationResponse);
        //
        /// Web service synchronous operation 'SetAudioSourceConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioSourceConfiguration(_ns1__SetAudioSourceConfiguration *ns1__SetAudioSourceConfiguration, ns1__SetConfigurationResponse &ns1__SetAudioSourceConfigurationResponse) { return this->SetAudioSourceConfiguration(NULL, NULL, ns1__SetAudioSourceConfiguration, ns1__SetAudioSourceConfigurationResponse); }
        /// Web service synchronous operation 'SetAudioSourceConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetAudioSourceConfiguration *ns1__SetAudioSourceConfiguration, ns1__SetConfigurationResponse &ns1__SetAudioSourceConfigurationResponse) { return this->send_SetAudioSourceConfiguration(soap_endpoint_url, soap_action, ns1__SetAudioSourceConfiguration) || this->recv_SetAudioSourceConfiguration(ns1__SetAudioSourceConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetAudioSourceConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetAudioSourceConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetAudioSourceConfiguration *ns1__SetAudioSourceConfiguration);
        /// Web service asynchronous operation 'recv_SetAudioSourceConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetAudioSourceConfiguration(ns1__SetConfigurationResponse &ns1__SetAudioSourceConfigurationResponse);
        //
        /// Web service synchronous operation 'SetAudioEncoderConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioEncoderConfiguration(_ns1__SetAudioEncoderConfiguration *ns1__SetAudioEncoderConfiguration, ns1__SetConfigurationResponse &ns1__SetAudioEncoderConfigurationResponse) { return this->SetAudioEncoderConfiguration(NULL, NULL, ns1__SetAudioEncoderConfiguration, ns1__SetAudioEncoderConfigurationResponse); }
        /// Web service synchronous operation 'SetAudioEncoderConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioEncoderConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetAudioEncoderConfiguration *ns1__SetAudioEncoderConfiguration, ns1__SetConfigurationResponse &ns1__SetAudioEncoderConfigurationResponse) { return this->send_SetAudioEncoderConfiguration(soap_endpoint_url, soap_action, ns1__SetAudioEncoderConfiguration) || this->recv_SetAudioEncoderConfiguration(ns1__SetAudioEncoderConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetAudioEncoderConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetAudioEncoderConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetAudioEncoderConfiguration *ns1__SetAudioEncoderConfiguration);
        /// Web service asynchronous operation 'recv_SetAudioEncoderConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetAudioEncoderConfiguration(ns1__SetConfigurationResponse &ns1__SetAudioEncoderConfigurationResponse);
        //
        /// Web service synchronous operation 'SetMetadataConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetMetadataConfiguration(_ns1__SetMetadataConfiguration *ns1__SetMetadataConfiguration, ns1__SetConfigurationResponse &ns1__SetMetadataConfigurationResponse) { return this->SetMetadataConfiguration(NULL, NULL, ns1__SetMetadataConfiguration, ns1__SetMetadataConfigurationResponse); }
        /// Web service synchronous operation 'SetMetadataConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetMetadataConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetMetadataConfiguration *ns1__SetMetadataConfiguration, ns1__SetConfigurationResponse &ns1__SetMetadataConfigurationResponse) { return this->send_SetMetadataConfiguration(soap_endpoint_url, soap_action, ns1__SetMetadataConfiguration) || this->recv_SetMetadataConfiguration(ns1__SetMetadataConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetMetadataConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetMetadataConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetMetadataConfiguration *ns1__SetMetadataConfiguration);
        /// Web service asynchronous operation 'recv_SetMetadataConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetMetadataConfiguration(ns1__SetConfigurationResponse &ns1__SetMetadataConfigurationResponse);
        //
        /// Web service synchronous operation 'SetAudioOutputConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioOutputConfiguration(_ns1__SetAudioOutputConfiguration *ns1__SetAudioOutputConfiguration, ns1__SetConfigurationResponse &ns1__SetAudioOutputConfigurationResponse) { return this->SetAudioOutputConfiguration(NULL, NULL, ns1__SetAudioOutputConfiguration, ns1__SetAudioOutputConfigurationResponse); }
        /// Web service synchronous operation 'SetAudioOutputConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetAudioOutputConfiguration *ns1__SetAudioOutputConfiguration, ns1__SetConfigurationResponse &ns1__SetAudioOutputConfigurationResponse) { return this->send_SetAudioOutputConfiguration(soap_endpoint_url, soap_action, ns1__SetAudioOutputConfiguration) || this->recv_SetAudioOutputConfiguration(ns1__SetAudioOutputConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetAudioOutputConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetAudioOutputConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetAudioOutputConfiguration *ns1__SetAudioOutputConfiguration);
        /// Web service asynchronous operation 'recv_SetAudioOutputConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetAudioOutputConfiguration(ns1__SetConfigurationResponse &ns1__SetAudioOutputConfigurationResponse);
        //
        /// Web service synchronous operation 'SetAudioDecoderConfiguration' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioDecoderConfiguration(_ns1__SetAudioDecoderConfiguration *ns1__SetAudioDecoderConfiguration, ns1__SetConfigurationResponse &ns1__SetAudioDecoderConfigurationResponse) { return this->SetAudioDecoderConfiguration(NULL, NULL, ns1__SetAudioDecoderConfiguration, ns1__SetAudioDecoderConfigurationResponse); }
        /// Web service synchronous operation 'SetAudioDecoderConfiguration' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetAudioDecoderConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetAudioDecoderConfiguration *ns1__SetAudioDecoderConfiguration, ns1__SetConfigurationResponse &ns1__SetAudioDecoderConfigurationResponse) { return this->send_SetAudioDecoderConfiguration(soap_endpoint_url, soap_action, ns1__SetAudioDecoderConfiguration) || this->recv_SetAudioDecoderConfiguration(ns1__SetAudioDecoderConfigurationResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetAudioDecoderConfiguration' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetAudioDecoderConfiguration(const char *soap_endpoint_url, const char *soap_action, _ns1__SetAudioDecoderConfiguration *ns1__SetAudioDecoderConfiguration);
        /// Web service asynchronous operation 'recv_SetAudioDecoderConfiguration' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetAudioDecoderConfiguration(ns1__SetConfigurationResponse &ns1__SetAudioDecoderConfigurationResponse);
        //
        /// Web service synchronous operation 'GetVideoSourceConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceConfigurationOptions(ns1__GetConfiguration *ns1__GetVideoSourceConfigurationOptions, _ns1__GetVideoSourceConfigurationOptionsResponse &ns1__GetVideoSourceConfigurationOptionsResponse) { return this->GetVideoSourceConfigurationOptions(NULL, NULL, ns1__GetVideoSourceConfigurationOptions, ns1__GetVideoSourceConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetVideoSourceConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetVideoSourceConfigurationOptions, _ns1__GetVideoSourceConfigurationOptionsResponse &ns1__GetVideoSourceConfigurationOptionsResponse) { return this->send_GetVideoSourceConfigurationOptions(soap_endpoint_url, soap_action, ns1__GetVideoSourceConfigurationOptions) || this->recv_GetVideoSourceConfigurationOptions(ns1__GetVideoSourceConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoSourceConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoSourceConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetVideoSourceConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetVideoSourceConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoSourceConfigurationOptions(_ns1__GetVideoSourceConfigurationOptionsResponse &ns1__GetVideoSourceConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetVideoEncoderConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoEncoderConfigurationOptions(ns1__GetConfiguration *ns1__GetVideoEncoderConfigurationOptions, _ns1__GetVideoEncoderConfigurationOptionsResponse &ns1__GetVideoEncoderConfigurationOptionsResponse) { return this->GetVideoEncoderConfigurationOptions(NULL, NULL, ns1__GetVideoEncoderConfigurationOptions, ns1__GetVideoEncoderConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetVideoEncoderConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoEncoderConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetVideoEncoderConfigurationOptions, _ns1__GetVideoEncoderConfigurationOptionsResponse &ns1__GetVideoEncoderConfigurationOptionsResponse) { return this->send_GetVideoEncoderConfigurationOptions(soap_endpoint_url, soap_action, ns1__GetVideoEncoderConfigurationOptions) || this->recv_GetVideoEncoderConfigurationOptions(ns1__GetVideoEncoderConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoEncoderConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoEncoderConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetVideoEncoderConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetVideoEncoderConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoEncoderConfigurationOptions(_ns1__GetVideoEncoderConfigurationOptionsResponse &ns1__GetVideoEncoderConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetAudioSourceConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSourceConfigurationOptions(ns1__GetConfiguration *ns1__GetAudioSourceConfigurationOptions, _ns1__GetAudioSourceConfigurationOptionsResponse &ns1__GetAudioSourceConfigurationOptionsResponse) { return this->GetAudioSourceConfigurationOptions(NULL, NULL, ns1__GetAudioSourceConfigurationOptions, ns1__GetAudioSourceConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetAudioSourceConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioSourceConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioSourceConfigurationOptions, _ns1__GetAudioSourceConfigurationOptionsResponse &ns1__GetAudioSourceConfigurationOptionsResponse) { return this->send_GetAudioSourceConfigurationOptions(soap_endpoint_url, soap_action, ns1__GetAudioSourceConfigurationOptions) || this->recv_GetAudioSourceConfigurationOptions(ns1__GetAudioSourceConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioSourceConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioSourceConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioSourceConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetAudioSourceConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioSourceConfigurationOptions(_ns1__GetAudioSourceConfigurationOptionsResponse &ns1__GetAudioSourceConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetAudioEncoderConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioEncoderConfigurationOptions(ns1__GetConfiguration *ns1__GetAudioEncoderConfigurationOptions, _ns1__GetAudioEncoderConfigurationOptionsResponse &ns1__GetAudioEncoderConfigurationOptionsResponse) { return this->GetAudioEncoderConfigurationOptions(NULL, NULL, ns1__GetAudioEncoderConfigurationOptions, ns1__GetAudioEncoderConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetAudioEncoderConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioEncoderConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioEncoderConfigurationOptions, _ns1__GetAudioEncoderConfigurationOptionsResponse &ns1__GetAudioEncoderConfigurationOptionsResponse) { return this->send_GetAudioEncoderConfigurationOptions(soap_endpoint_url, soap_action, ns1__GetAudioEncoderConfigurationOptions) || this->recv_GetAudioEncoderConfigurationOptions(ns1__GetAudioEncoderConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioEncoderConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioEncoderConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioEncoderConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetAudioEncoderConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioEncoderConfigurationOptions(_ns1__GetAudioEncoderConfigurationOptionsResponse &ns1__GetAudioEncoderConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetMetadataConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetMetadataConfigurationOptions(ns1__GetConfiguration *ns1__GetMetadataConfigurationOptions, _ns1__GetMetadataConfigurationOptionsResponse &ns1__GetMetadataConfigurationOptionsResponse) { return this->GetMetadataConfigurationOptions(NULL, NULL, ns1__GetMetadataConfigurationOptions, ns1__GetMetadataConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetMetadataConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetMetadataConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetMetadataConfigurationOptions, _ns1__GetMetadataConfigurationOptionsResponse &ns1__GetMetadataConfigurationOptionsResponse) { return this->send_GetMetadataConfigurationOptions(soap_endpoint_url, soap_action, ns1__GetMetadataConfigurationOptions) || this->recv_GetMetadataConfigurationOptions(ns1__GetMetadataConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetMetadataConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetMetadataConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetMetadataConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetMetadataConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetMetadataConfigurationOptions(_ns1__GetMetadataConfigurationOptionsResponse &ns1__GetMetadataConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetAudioOutputConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputConfigurationOptions(ns1__GetConfiguration *ns1__GetAudioOutputConfigurationOptions, _ns1__GetAudioOutputConfigurationOptionsResponse &ns1__GetAudioOutputConfigurationOptionsResponse) { return this->GetAudioOutputConfigurationOptions(NULL, NULL, ns1__GetAudioOutputConfigurationOptions, ns1__GetAudioOutputConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetAudioOutputConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioOutputConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioOutputConfigurationOptions, _ns1__GetAudioOutputConfigurationOptionsResponse &ns1__GetAudioOutputConfigurationOptionsResponse) { return this->send_GetAudioOutputConfigurationOptions(soap_endpoint_url, soap_action, ns1__GetAudioOutputConfigurationOptions) || this->recv_GetAudioOutputConfigurationOptions(ns1__GetAudioOutputConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioOutputConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioOutputConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioOutputConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetAudioOutputConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioOutputConfigurationOptions(_ns1__GetAudioOutputConfigurationOptionsResponse &ns1__GetAudioOutputConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetAudioDecoderConfigurationOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioDecoderConfigurationOptions(ns1__GetConfiguration *ns1__GetAudioDecoderConfigurationOptions, _ns1__GetAudioDecoderConfigurationOptionsResponse &ns1__GetAudioDecoderConfigurationOptionsResponse) { return this->GetAudioDecoderConfigurationOptions(NULL, NULL, ns1__GetAudioDecoderConfigurationOptions, ns1__GetAudioDecoderConfigurationOptionsResponse); }
        /// Web service synchronous operation 'GetAudioDecoderConfigurationOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetAudioDecoderConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioDecoderConfigurationOptions, _ns1__GetAudioDecoderConfigurationOptionsResponse &ns1__GetAudioDecoderConfigurationOptionsResponse) { return this->send_GetAudioDecoderConfigurationOptions(soap_endpoint_url, soap_action, ns1__GetAudioDecoderConfigurationOptions) || this->recv_GetAudioDecoderConfigurationOptions(ns1__GetAudioDecoderConfigurationOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetAudioDecoderConfigurationOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetAudioDecoderConfigurationOptions(const char *soap_endpoint_url, const char *soap_action, ns1__GetConfiguration *ns1__GetAudioDecoderConfigurationOptions);
        /// Web service asynchronous operation 'recv_GetAudioDecoderConfigurationOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetAudioDecoderConfigurationOptions(_ns1__GetAudioDecoderConfigurationOptionsResponse &ns1__GetAudioDecoderConfigurationOptionsResponse);
        //
        /// Web service synchronous operation 'GetVideoEncoderInstances' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoEncoderInstances(_ns1__GetVideoEncoderInstances *ns1__GetVideoEncoderInstances, _ns1__GetVideoEncoderInstancesResponse &ns1__GetVideoEncoderInstancesResponse) { return this->GetVideoEncoderInstances(NULL, NULL, ns1__GetVideoEncoderInstances, ns1__GetVideoEncoderInstancesResponse); }
        /// Web service synchronous operation 'GetVideoEncoderInstances' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoEncoderInstances(const char *soap_endpoint_url, const char *soap_action, _ns1__GetVideoEncoderInstances *ns1__GetVideoEncoderInstances, _ns1__GetVideoEncoderInstancesResponse &ns1__GetVideoEncoderInstancesResponse) { return this->send_GetVideoEncoderInstances(soap_endpoint_url, soap_action, ns1__GetVideoEncoderInstances) || this->recv_GetVideoEncoderInstances(ns1__GetVideoEncoderInstancesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoEncoderInstances' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoEncoderInstances(const char *soap_endpoint_url, const char *soap_action, _ns1__GetVideoEncoderInstances *ns1__GetVideoEncoderInstances);
        /// Web service asynchronous operation 'recv_GetVideoEncoderInstances' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoEncoderInstances(_ns1__GetVideoEncoderInstancesResponse &ns1__GetVideoEncoderInstancesResponse);
        //
        /// Web service synchronous operation 'GetStreamUri' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetStreamUri(_ns1__GetStreamUri *ns1__GetStreamUri, _ns1__GetStreamUriResponse &ns1__GetStreamUriResponse) { return this->GetStreamUri(NULL, NULL, ns1__GetStreamUri, ns1__GetStreamUriResponse); }
        /// Web service synchronous operation 'GetStreamUri' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetStreamUri(const char *soap_endpoint_url, const char *soap_action, _ns1__GetStreamUri *ns1__GetStreamUri, _ns1__GetStreamUriResponse &ns1__GetStreamUriResponse) { return this->send_GetStreamUri(soap_endpoint_url, soap_action, ns1__GetStreamUri) || this->recv_GetStreamUri(ns1__GetStreamUriResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetStreamUri' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetStreamUri(const char *soap_endpoint_url, const char *soap_action, _ns1__GetStreamUri *ns1__GetStreamUri);
        /// Web service asynchronous operation 'recv_GetStreamUri' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetStreamUri(_ns1__GetStreamUriResponse &ns1__GetStreamUriResponse);
        //
        /// Web service synchronous operation 'StartMulticastStreaming' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int StartMulticastStreaming(ns1__StartStopMulticastStreaming *ns1__StartMulticastStreaming, ns1__SetConfigurationResponse &ns1__StartMulticastStreamingResponse) { return this->StartMulticastStreaming(NULL, NULL, ns1__StartMulticastStreaming, ns1__StartMulticastStreamingResponse); }
        /// Web service synchronous operation 'StartMulticastStreaming' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int StartMulticastStreaming(const char *soap_endpoint_url, const char *soap_action, ns1__StartStopMulticastStreaming *ns1__StartMulticastStreaming, ns1__SetConfigurationResponse &ns1__StartMulticastStreamingResponse) { return this->send_StartMulticastStreaming(soap_endpoint_url, soap_action, ns1__StartMulticastStreaming) || this->recv_StartMulticastStreaming(ns1__StartMulticastStreamingResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_StartMulticastStreaming' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_StartMulticastStreaming(const char *soap_endpoint_url, const char *soap_action, ns1__StartStopMulticastStreaming *ns1__StartMulticastStreaming);
        /// Web service asynchronous operation 'recv_StartMulticastStreaming' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_StartMulticastStreaming(ns1__SetConfigurationResponse &ns1__StartMulticastStreamingResponse);
        //
        /// Web service synchronous operation 'StopMulticastStreaming' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int StopMulticastStreaming(ns1__StartStopMulticastStreaming *ns1__StopMulticastStreaming, ns1__SetConfigurationResponse &ns1__StopMulticastStreamingResponse) { return this->StopMulticastStreaming(NULL, NULL, ns1__StopMulticastStreaming, ns1__StopMulticastStreamingResponse); }
        /// Web service synchronous operation 'StopMulticastStreaming' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int StopMulticastStreaming(const char *soap_endpoint_url, const char *soap_action, ns1__StartStopMulticastStreaming *ns1__StopMulticastStreaming, ns1__SetConfigurationResponse &ns1__StopMulticastStreamingResponse) { return this->send_StopMulticastStreaming(soap_endpoint_url, soap_action, ns1__StopMulticastStreaming) || this->recv_StopMulticastStreaming(ns1__StopMulticastStreamingResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_StopMulticastStreaming' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_StopMulticastStreaming(const char *soap_endpoint_url, const char *soap_action, ns1__StartStopMulticastStreaming *ns1__StopMulticastStreaming);
        /// Web service asynchronous operation 'recv_StopMulticastStreaming' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_StopMulticastStreaming(ns1__SetConfigurationResponse &ns1__StopMulticastStreamingResponse);
        //
        /// Web service synchronous operation 'SetSynchronizationPoint' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetSynchronizationPoint(_ns1__SetSynchronizationPoint *ns1__SetSynchronizationPoint, _ns1__SetSynchronizationPointResponse &ns1__SetSynchronizationPointResponse) { return this->SetSynchronizationPoint(NULL, NULL, ns1__SetSynchronizationPoint, ns1__SetSynchronizationPointResponse); }
        /// Web service synchronous operation 'SetSynchronizationPoint' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetSynchronizationPoint(const char *soap_endpoint_url, const char *soap_action, _ns1__SetSynchronizationPoint *ns1__SetSynchronizationPoint, _ns1__SetSynchronizationPointResponse &ns1__SetSynchronizationPointResponse) { return this->send_SetSynchronizationPoint(soap_endpoint_url, soap_action, ns1__SetSynchronizationPoint) || this->recv_SetSynchronizationPoint(ns1__SetSynchronizationPointResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetSynchronizationPoint' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetSynchronizationPoint(const char *soap_endpoint_url, const char *soap_action, _ns1__SetSynchronizationPoint *ns1__SetSynchronizationPoint);
        /// Web service asynchronous operation 'recv_SetSynchronizationPoint' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetSynchronizationPoint(_ns1__SetSynchronizationPointResponse &ns1__SetSynchronizationPointResponse);
        //
        /// Web service synchronous operation 'GetSnapshotUri' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetSnapshotUri(_ns1__GetSnapshotUri *ns1__GetSnapshotUri, _ns1__GetSnapshotUriResponse &ns1__GetSnapshotUriResponse) { return this->GetSnapshotUri(NULL, NULL, ns1__GetSnapshotUri, ns1__GetSnapshotUriResponse); }
        /// Web service synchronous operation 'GetSnapshotUri' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetSnapshotUri(const char *soap_endpoint_url, const char *soap_action, _ns1__GetSnapshotUri *ns1__GetSnapshotUri, _ns1__GetSnapshotUriResponse &ns1__GetSnapshotUriResponse) { return this->send_GetSnapshotUri(soap_endpoint_url, soap_action, ns1__GetSnapshotUri) || this->recv_GetSnapshotUri(ns1__GetSnapshotUriResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetSnapshotUri' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetSnapshotUri(const char *soap_endpoint_url, const char *soap_action, _ns1__GetSnapshotUri *ns1__GetSnapshotUri);
        /// Web service asynchronous operation 'recv_GetSnapshotUri' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetSnapshotUri(_ns1__GetSnapshotUriResponse &ns1__GetSnapshotUriResponse);
        //
        /// Web service synchronous operation 'GetVideoSourceModes' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceModes(_ns1__GetVideoSourceModes *ns1__GetVideoSourceModes, _ns1__GetVideoSourceModesResponse &ns1__GetVideoSourceModesResponse) { return this->GetVideoSourceModes(NULL, NULL, ns1__GetVideoSourceModes, ns1__GetVideoSourceModesResponse); }
        /// Web service synchronous operation 'GetVideoSourceModes' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetVideoSourceModes(const char *soap_endpoint_url, const char *soap_action, _ns1__GetVideoSourceModes *ns1__GetVideoSourceModes, _ns1__GetVideoSourceModesResponse &ns1__GetVideoSourceModesResponse) { return this->send_GetVideoSourceModes(soap_endpoint_url, soap_action, ns1__GetVideoSourceModes) || this->recv_GetVideoSourceModes(ns1__GetVideoSourceModesResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetVideoSourceModes' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetVideoSourceModes(const char *soap_endpoint_url, const char *soap_action, _ns1__GetVideoSourceModes *ns1__GetVideoSourceModes);
        /// Web service asynchronous operation 'recv_GetVideoSourceModes' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetVideoSourceModes(_ns1__GetVideoSourceModesResponse &ns1__GetVideoSourceModesResponse);
        //
        /// Web service synchronous operation 'SetVideoSourceMode' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoSourceMode(_ns1__SetVideoSourceMode *ns1__SetVideoSourceMode, _ns1__SetVideoSourceModeResponse &ns1__SetVideoSourceModeResponse) { return this->SetVideoSourceMode(NULL, NULL, ns1__SetVideoSourceMode, ns1__SetVideoSourceModeResponse); }
        /// Web service synchronous operation 'SetVideoSourceMode' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetVideoSourceMode(const char *soap_endpoint_url, const char *soap_action, _ns1__SetVideoSourceMode *ns1__SetVideoSourceMode, _ns1__SetVideoSourceModeResponse &ns1__SetVideoSourceModeResponse) { return this->send_SetVideoSourceMode(soap_endpoint_url, soap_action, ns1__SetVideoSourceMode) || this->recv_SetVideoSourceMode(ns1__SetVideoSourceModeResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetVideoSourceMode' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetVideoSourceMode(const char *soap_endpoint_url, const char *soap_action, _ns1__SetVideoSourceMode *ns1__SetVideoSourceMode);
        /// Web service asynchronous operation 'recv_SetVideoSourceMode' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetVideoSourceMode(_ns1__SetVideoSourceModeResponse &ns1__SetVideoSourceModeResponse);
        //
        /// Web service synchronous operation 'GetOSDs' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetOSDs(_ns1__GetOSDs *ns1__GetOSDs, _ns1__GetOSDsResponse &ns1__GetOSDsResponse) { return this->GetOSDs(NULL, NULL, ns1__GetOSDs, ns1__GetOSDsResponse); }
        /// Web service synchronous operation 'GetOSDs' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetOSDs(const char *soap_endpoint_url, const char *soap_action, _ns1__GetOSDs *ns1__GetOSDs, _ns1__GetOSDsResponse &ns1__GetOSDsResponse) { return this->send_GetOSDs(soap_endpoint_url, soap_action, ns1__GetOSDs) || this->recv_GetOSDs(ns1__GetOSDsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetOSDs' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetOSDs(const char *soap_endpoint_url, const char *soap_action, _ns1__GetOSDs *ns1__GetOSDs);
        /// Web service asynchronous operation 'recv_GetOSDs' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetOSDs(_ns1__GetOSDsResponse &ns1__GetOSDsResponse);
        //
        /// Web service synchronous operation 'GetOSDOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetOSDOptions(_ns1__GetOSDOptions *ns1__GetOSDOptions, _ns1__GetOSDOptionsResponse &ns1__GetOSDOptionsResponse) { return this->GetOSDOptions(NULL, NULL, ns1__GetOSDOptions, ns1__GetOSDOptionsResponse); }
        /// Web service synchronous operation 'GetOSDOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetOSDOptions(const char *soap_endpoint_url, const char *soap_action, _ns1__GetOSDOptions *ns1__GetOSDOptions, _ns1__GetOSDOptionsResponse &ns1__GetOSDOptionsResponse) { return this->send_GetOSDOptions(soap_endpoint_url, soap_action, ns1__GetOSDOptions) || this->recv_GetOSDOptions(ns1__GetOSDOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetOSDOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetOSDOptions(const char *soap_endpoint_url, const char *soap_action, _ns1__GetOSDOptions *ns1__GetOSDOptions);
        /// Web service asynchronous operation 'recv_GetOSDOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetOSDOptions(_ns1__GetOSDOptionsResponse &ns1__GetOSDOptionsResponse);
        //
        /// Web service synchronous operation 'SetOSD' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetOSD(_ns1__SetOSD *ns1__SetOSD, ns1__SetConfigurationResponse &ns1__SetOSDResponse) { return this->SetOSD(NULL, NULL, ns1__SetOSD, ns1__SetOSDResponse); }
        /// Web service synchronous operation 'SetOSD' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetOSD(const char *soap_endpoint_url, const char *soap_action, _ns1__SetOSD *ns1__SetOSD, ns1__SetConfigurationResponse &ns1__SetOSDResponse) { return this->send_SetOSD(soap_endpoint_url, soap_action, ns1__SetOSD) || this->recv_SetOSD(ns1__SetOSDResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetOSD' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetOSD(const char *soap_endpoint_url, const char *soap_action, _ns1__SetOSD *ns1__SetOSD);
        /// Web service asynchronous operation 'recv_SetOSD' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetOSD(ns1__SetConfigurationResponse &ns1__SetOSDResponse);
        //
        /// Web service synchronous operation 'CreateOSD' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreateOSD(_ns1__CreateOSD *ns1__CreateOSD, _ns1__CreateOSDResponse &ns1__CreateOSDResponse) { return this->CreateOSD(NULL, NULL, ns1__CreateOSD, ns1__CreateOSDResponse); }
        /// Web service synchronous operation 'CreateOSD' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreateOSD(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateOSD *ns1__CreateOSD, _ns1__CreateOSDResponse &ns1__CreateOSDResponse) { return this->send_CreateOSD(soap_endpoint_url, soap_action, ns1__CreateOSD) || this->recv_CreateOSD(ns1__CreateOSDResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreateOSD' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreateOSD(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateOSD *ns1__CreateOSD);
        /// Web service asynchronous operation 'recv_CreateOSD' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreateOSD(_ns1__CreateOSDResponse &ns1__CreateOSDResponse);
        //
        /// Web service synchronous operation 'DeleteOSD' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteOSD(_ns1__DeleteOSD *ns1__DeleteOSD, ns1__SetConfigurationResponse &ns1__DeleteOSDResponse) { return this->DeleteOSD(NULL, NULL, ns1__DeleteOSD, ns1__DeleteOSDResponse); }
        /// Web service synchronous operation 'DeleteOSD' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteOSD(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteOSD *ns1__DeleteOSD, ns1__SetConfigurationResponse &ns1__DeleteOSDResponse) { return this->send_DeleteOSD(soap_endpoint_url, soap_action, ns1__DeleteOSD) || this->recv_DeleteOSD(ns1__DeleteOSDResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteOSD' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteOSD(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteOSD *ns1__DeleteOSD);
        /// Web service asynchronous operation 'recv_DeleteOSD' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteOSD(ns1__SetConfigurationResponse &ns1__DeleteOSDResponse);
        //
        /// Web service synchronous operation 'GetMasks' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetMasks(_ns1__GetMasks *ns1__GetMasks, _ns1__GetMasksResponse &ns1__GetMasksResponse) { return this->GetMasks(NULL, NULL, ns1__GetMasks, ns1__GetMasksResponse); }
        /// Web service synchronous operation 'GetMasks' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetMasks(const char *soap_endpoint_url, const char *soap_action, _ns1__GetMasks *ns1__GetMasks, _ns1__GetMasksResponse &ns1__GetMasksResponse) { return this->send_GetMasks(soap_endpoint_url, soap_action, ns1__GetMasks) || this->recv_GetMasks(ns1__GetMasksResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetMasks' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetMasks(const char *soap_endpoint_url, const char *soap_action, _ns1__GetMasks *ns1__GetMasks);
        /// Web service asynchronous operation 'recv_GetMasks' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetMasks(_ns1__GetMasksResponse &ns1__GetMasksResponse);
        //
        /// Web service synchronous operation 'GetMaskOptions' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int GetMaskOptions(_ns1__GetMaskOptions *ns1__GetMaskOptions, _ns1__GetMaskOptionsResponse &ns1__GetMaskOptionsResponse) { return this->GetMaskOptions(NULL, NULL, ns1__GetMaskOptions, ns1__GetMaskOptionsResponse); }
        /// Web service synchronous operation 'GetMaskOptions' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int GetMaskOptions(const char *soap_endpoint_url, const char *soap_action, _ns1__GetMaskOptions *ns1__GetMaskOptions, _ns1__GetMaskOptionsResponse &ns1__GetMaskOptionsResponse) { return this->send_GetMaskOptions(soap_endpoint_url, soap_action, ns1__GetMaskOptions) || this->recv_GetMaskOptions(ns1__GetMaskOptionsResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_GetMaskOptions' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_GetMaskOptions(const char *soap_endpoint_url, const char *soap_action, _ns1__GetMaskOptions *ns1__GetMaskOptions);
        /// Web service asynchronous operation 'recv_GetMaskOptions' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_GetMaskOptions(_ns1__GetMaskOptionsResponse &ns1__GetMaskOptionsResponse);
        //
        /// Web service synchronous operation 'SetMask' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SetMask(_ns1__SetMask *ns1__SetMask, ns1__SetConfigurationResponse &ns1__SetMaskResponse) { return this->SetMask(NULL, NULL, ns1__SetMask, ns1__SetMaskResponse); }
        /// Web service synchronous operation 'SetMask' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SetMask(const char *soap_endpoint_url, const char *soap_action, _ns1__SetMask *ns1__SetMask, ns1__SetConfigurationResponse &ns1__SetMaskResponse) { return this->send_SetMask(soap_endpoint_url, soap_action, ns1__SetMask) || this->recv_SetMask(ns1__SetMaskResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SetMask' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SetMask(const char *soap_endpoint_url, const char *soap_action, _ns1__SetMask *ns1__SetMask);
        /// Web service asynchronous operation 'recv_SetMask' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SetMask(ns1__SetConfigurationResponse &ns1__SetMaskResponse);
        //
        /// Web service synchronous operation 'CreateMask' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int CreateMask(_ns1__CreateMask *ns1__CreateMask, _ns1__CreateMaskResponse &ns1__CreateMaskResponse) { return this->CreateMask(NULL, NULL, ns1__CreateMask, ns1__CreateMaskResponse); }
        /// Web service synchronous operation 'CreateMask' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int CreateMask(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateMask *ns1__CreateMask, _ns1__CreateMaskResponse &ns1__CreateMaskResponse) { return this->send_CreateMask(soap_endpoint_url, soap_action, ns1__CreateMask) || this->recv_CreateMask(ns1__CreateMaskResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_CreateMask' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_CreateMask(const char *soap_endpoint_url, const char *soap_action, _ns1__CreateMask *ns1__CreateMask);
        /// Web service asynchronous operation 'recv_CreateMask' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_CreateMask(_ns1__CreateMaskResponse &ns1__CreateMaskResponse);
        //
        /// Web service synchronous operation 'DeleteMask' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteMask(_ns1__DeleteMask *ns1__DeleteMask, ns1__SetConfigurationResponse &ns1__DeleteMaskResponse) { return this->DeleteMask(NULL, NULL, ns1__DeleteMask, ns1__DeleteMaskResponse); }
        /// Web service synchronous operation 'DeleteMask' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int DeleteMask(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteMask *ns1__DeleteMask, ns1__SetConfigurationResponse &ns1__DeleteMaskResponse) { return this->send_DeleteMask(soap_endpoint_url, soap_action, ns1__DeleteMask) || this->recv_DeleteMask(ns1__DeleteMaskResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_DeleteMask' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_DeleteMask(const char *soap_endpoint_url, const char *soap_action, _ns1__DeleteMask *ns1__DeleteMask);
        /// Web service asynchronous operation 'recv_DeleteMask' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_DeleteMask(ns1__SetConfigurationResponse &ns1__DeleteMaskResponse);
    };
#endif
